name: Publish Nugets

# Controls when the workflow will run
on:
  push:
    branches:
      - main
jobs:
  publish_nuget:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job 
    steps:
      - uses: actions/checkout@v3
      - name: Add Org Nuget Source
        run: dotnet nuget add source --username mihail-brinza --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/down-cast/index.json"
      - run: dotnet pack -c Release -o . src/Downcast.Common.Data.Validators/Downcast.Common.Data.Validators.csproj
      - run: dotnet pack -c Release -o . src/Downcast.Common.Errors/Downcast.Common.Errors.csproj
      - run: dotnet pack -c Release -o . src/Downcast.Common.Errors.Handler/Downcast.Common.Errors.Handler.csproj
      - run: dotnet pack -c Release -o . src/Downcast.Common.HttpClient.Extensions/Downcast.Common.HttpClient.Extensions.csproj
      - run: dotnet pack -c Release -o . src/Downcast.Common.Logging/Downcast.Common.Logging.csproj
      - name: Publish Nugets
        run: dotnet nuget push *.nupkg -k ${{ secrets.GITHUB_TOKEN }} -s "github" --skip-duplicate