name: publish to nuget
on:
  push:
    branches:
      - main
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Downcast.Common.Logging
        id: publish_logging_nuget
        uses: Rebel028/publish-nuget@v2.7.0
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: src/Downcast.Common.Logging/Downcast.Common.Logging.csproj
          
          # Configuration to build and package
          BUILD_CONFIGURATION: Release
          
          # Platform target to compile (default is empty/AnyCPU)
          # BUILD_PLATFORM: x64          
          
          # NuGet package id, used for version detection & defaults to project name
          PACKAGE_NAME: Downcast.Common.Logging
          
          # Filepath with version info, relative to root of repository & defaults to PROJECT_FILE_PATH
          VERSION_FILE_PATH: src/Downcast.Common.Logging/Directory.Build.props

          # Regex pattern to extract version info in a capturing group
          # VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          
          # Useful with external providers like Nerdbank.GitVersioning, ignores VERSION_FILE_PATH & VERSION_REGEX
          # VERSION_STATIC: 1.0.0

          # Flag to toggle git tagging, enabled by default
          # TAG_COMMIT: true

          # Format of the git tag, [*] gets replaced with actual version
          # TAG_FORMAT: v*
          
          # Required for packages pushed to Github Package Registry. User allowed to push to repository, defaults to GITHUB_ACTOR (user that triggered the action)
          # GITHUB_USER: # optional
          
          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.GITHUB_TOKEN}}

          # NuGet server uri hosting the packages, defaults to https://api.nuget.org
          NUGET_SOURCE: https://nuget.pkg.github.com/down-cast

          # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
          # INCLUDE_SYMBOLS: false
          
      - name: Downcast.Common.HttpClient.Extensions
        id: publish_http_client_nuget
        uses: Rebel028/publish-nuget@v2.7.0
        with:
          PROJECT_FILE_PATH: src/Downcast.Common.HttpClient.Extensions/Downcast.Common.HttpClient.Extensions.csproj
          PACKAGE_NAME: Downcast.Common.HttpClient.Extensions
          VERSION_FILE_PATH: src/Downcast.Common.HttpClient.Extensions/Directory.Build.props
          NUGET_KEY: ${{secrets.GITHUB_TOKEN}}
          NUGET_SOURCE: https://nuget.pkg.github.com/down-cast